"""empty message

Revision ID: 0618e7d6c610
Revises: 2948378e674d
Create Date: 2016-05-14 00:36:51.149654

"""

# revision identifiers, used by Alembic.
revision = '0618e7d6c610'
down_revision = '2948378e674d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('problem', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('verified_string', sa.Text(), nullable=True))
    op.drop_column('task', 'output')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('task', 'verified_string')
    op.drop_column('task', 'status')
    op.drop_column('task', 'problem')
    op.drop_column('task', 'answer')
    ### end Alembic commands ###
