"""empty message

Revision ID: 0fb83c055f74
Revises: 986b38df5730
Create Date: 2016-05-31 13:11:00.441666

"""

# revision identifiers, used by Alembic.
revision = '0fb83c055f74'
down_revision = '986b38df5730'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('article_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'article_id')
    ### end Alembic commands ###
