"""empty message

Revision ID: 150df1711f56
Revises: 5053d1204044
Create Date: 2016-08-09 11:56:08.940321

"""

# revision identifiers, used by Alembic.
revision = '150df1711f56'
down_revision = '5053d1204044'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('source', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'source')
    ### end Alembic commands ###
