"""empty message

Revision ID: 5053d1204044
Revises: 5121245e5378
Create Date: 2016-08-08 15:07:14.219398

"""

# revision identifiers, used by Alembic.
revision = '5053d1204044'
down_revision = '5121245e5378'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('link_hit_ids', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'link_hit_ids')
    ### end Alembic commands ###
