"""empty message

Revision ID: 5e8aab0023c8
Revises: 150df1711f56
Create Date: 2016-08-09 12:06:07.374858

"""

# revision identifiers, used by Alembic.
revision = '5e8aab0023c8'
down_revision = '150df1711f56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('server', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'server')
    ### end Alembic commands ###
