"""empty message

Revision ID: 84d55397aaad
Revises: 0fb83c055f74
Create Date: 2016-08-03 12:13:08.784841

"""

# revision identifiers, used by Alembic.
revision = '84d55397aaad'
down_revision = '0fb83c055f74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('common_idea', sa.Text(), nullable=True))
    op.add_column('link', sa.Column('thesis_statement_relevance_ids', sa.Text(), nullable=True))
    op.add_column('link', sa.Column('topic_sentence_idx', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'topic_sentence_idx')
    op.drop_column('link', 'thesis_statement_relevance_ids')
    op.drop_column('link', 'common_idea')
    ### end Alembic commands ###
