"""empty message

Revision ID: 92148da0a623
Revises: a515b7022942
Create Date: 2016-09-13 01:07:22.649817

"""

# revision identifiers, used by Alembic.
revision = '92148da0a623'
down_revision = 'a515b7022942'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goldenstructure', sa.Column('irrelevance', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goldenstructure', 'irrelevance')
    ### end Alembic commands ###
