"""empty message

Revision ID: 93ce56b9633a
Revises: 61cb756d6d18
Create Date: 2016-05-20 20:21:53.492747

"""

# revision identifiers, used by Alembic.
revision = '93ce56b9633a'
down_revision = '61cb756d6d18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('finished_time', sa.DateTime(), nullable=True),
    sa.Column('workflow_type', sa.Text(), nullable=True),
    sa.Column('topic_hit_ids', sa.Text(), nullable=True),
    sa.Column('relevance_hit_ids', sa.Text(), nullable=True),
    sa.Column('relation_hit_ids', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow')
    ### end Alembic commands ###
