"""empty message

Revision ID: 986b38df5730
Revises: 93ce56b9633a
Create Date: 2016-05-31 12:40:51.262655

"""

# revision identifiers, used by Alembic.
revision = '986b38df5730'
down_revision = '93ce56b9633a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('authors', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('source', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('year', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'year')
    op.drop_column('article', 'source')
    op.drop_column('article', 'authors')
    ### end Alembic commands ###
