"""empty message

Revision ID: a102a1e49e62
Revises: 84d55397aaad
Create Date: 2016-08-03 13:36:03.055602

"""

# revision identifiers, used by Alembic.
revision = 'a102a1e49e62'
down_revision = '84d55397aaad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('irrelevance_check', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'irrelevance_check')
    ### end Alembic commands ###
