"""empty message

Revision ID: a2b4b3057c2c
Revises: 3d9b46af0171
Create Date: 2016-05-17 18:54:16.994594

"""

# revision identifiers, used by Alembic.
revision = 'a2b4b3057c2c'
down_revision = '3d9b46af0171'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignment_id', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('hit_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'hit_id')
    op.drop_column('task', 'assignment_id')
    ### end Alembic commands ###
