"""empty message

Revision ID: a515b7022942
Revises: 5e8aab0023c8
Create Date: 2016-08-10 16:18:48.472941

"""

# revision identifiers, used by Alembic.
revision = 'a515b7022942'
down_revision = '5e8aab0023c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('rating', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'rating')
    ### end Alembic commands ###
